accurate/admin/accu/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function(){
 
 		/*user*/
 		Route::resource('user', 'User\UserController');

		Route::resource('roles','Roles\RoleController');
		Route::resource('users','Roles\UserController');
		Route::resource('banner','CMS\BannerController');
        Route::resource('pages','CMS\PagesController');
		/*Category*/
		Route::resource('category','Category\CategoryController');
		Route::resource('sub_category','Category\SubCategoryController');
		Route::resource('sub_sub_category','Category\SubSubCategoryController');
		Route::resource('sub_sub_sub_category','Category\SubSubSubContoller');

		/*Voucher*/
		Route::resource('voucher','Voucher\VoucherController');

		/*Inventory*/
		Route::resource('product','Inventory\ProductController');
		Route::resource('product_size','Inventory\ProductsizeController');
		Route::resource('stock','Inventory\StockController');

		/*query Section*/
		Route::get('support/query','Query\QueryController@view_support');
		Route::get('training/query','Query\QueryController@view_training');
		Route::get('contact/query','Query\QueryController@view_contact');

		/*Pincode Section*/
		Route::resource('pincode','Pincode\PincodeController');
		Route::get('pincode/delete/{id}','Pincode\PincodeController@delete')->name('pincode.delete');

		/*Orders*/
		Route::resource('orders','Order\OrderController');

});

accurate/admin/accu/resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>@yield('title')</title>
   @include('layouts.css')
</head>
<body class="skin-blue fixed sidebar-mini sidebar-mini-expand-feature">
<div class="wrapper">
  <!-- Sidebar -->
   @include('layouts.header')
      <div class="content-wrapper">
          @yield('content')
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="container">
          <div class="pull-right hidden-xs">
          </div>
          <strong>Copyright &copy; 2019-2020 <a href="https://techosoft.in/" target="_blank">TechoSoft Technologies</a></strong>
        </div>
      </footer>
    </div>
@include('layouts.notification')
@include('layouts.js')
</body>
</html>

accurate/admin/accu/resources/views/layouts/css.blade.php
   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="{{URL::To('bower_components/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{URL::To('bower_components/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{URL::To('bower_components/Ionicons/css/ionicons.min.css')}}" rel="stylesheet">
    <link href="{{URL::To('dist/css/AdminLTE.min.css')}}" rel="stylesheet">
    <link href="{{URL::To('plugins/iCheck/square/blue.css')}}" rel="stylesheet"> 
    <link href="{{URL::To('dist/css/skins/_all-skins.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link href="{{URL::To('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet"> 
    <link rel="stylesheet" href="{{URL::To('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
    <link rel="stylesheet" href="{{URL::to('dist/css/skins/_all-skins.min.css')}}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
     <link rel="stylesheet" href="{{URL::to('bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="{{URL::to('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
   <!-- Bootstrap time Picker -->
  <link rel="stylesheet" href="{{URL::to('plugins/timepicker/bootstrap-timepicker.min.css')}}">
  <link rel="stylesheet" href="{{URL::to('bower_components/select2/dist/css/select2.min.css')}}">

accurate/admin/accu/resources/views/layouts/header.blade.php
 <header class="main-header">
    <!-- Logo -->
    <a href="{{URL::to('/')}}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>E</b>S</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Accurate</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{URL::to('dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
              <span class="hidden-xs">Admin</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{URL::to('dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

                <p>
                    Admin
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a class="btn btn-default btn-flat" href="javascript:void(0)" onclick="event.preventDefault(); document.getElementById('logout-form').submit(); ">Sign out</a>
                     <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                     </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{URL::to('dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Admin</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      @include('layouts.menu')
    </section>
    <!-- /.sidebar -->
  </aside>

accurate/admin/accu/resources/views/layouts/js.blade.php
    <script src="{{URL::To('bower_components/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{URL::To('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <script src="{{URL::To('bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
    <script src="{{URL::To('bower_components/fastclick/lib/fastclick.js')}}"></script>
    <script src="{{URL::To('dist/js/adminlte.min.js')}}"></script>
    <script src="{{URL::To('dist/js/demo.js')}}"></script>
    <script src="{{URL::To('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{URL::To('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{URL::To('bower_components/ckeditor/ckeditor.js')}}"></script>
    <script src="{{URL::To('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="{{URL::to('bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
    <script src="{{URL::to('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script> 
    <script src="{{URL::to('plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>
    <script src="{{URL::to('bower_components/moment/min/moment.min.js')}}"></script>
    <script src="{{URL::to('plugins/input-mask/jquery.inputmask.js')}}"></script>
    <script src="{{URL::to('plugins/input-mask/jquery.inputmask.date.extensions.js')}}"></script>
    <script src="{{URL::to('plugins/input-mask/jquery.inputmask.extensions.js')}}"></script>
    <!-- Select2 -->
    <script src="{{URL::to('bower_components/select2/dist/js/select2.full.min.js')}}"></script>

    <!-- Datatables -->
   <script type="text/javascript" src="{{url::to('/js/dataTables.buttons.min.js')}}"></script>
   <script type="text/javascript" src="{{url::to('js/buttons.flash.min.js')}}"></script>
  <script type="text/javascript" src="{{url::to('js/jszip.min.js')}}"></script>
  <script type="text/javascript" src="{{url::to('js/pdfmake.min.js')}}"></script>
  <script type="text/javascript" src="{{url::to('js/vfs_fonts.js')}}"></script>
  <script type="text/javascript" src="{{url::to('js/buttons.html5.min.js')}}"></script>
  <script type="text/javascript" src="{{url::to('js/buttons.print.min.js')}}"></script>
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

<script>
  $(function () {
        //Initialize Select2 Elements
    $('.select2').select2()
    //Date picker
    $('#datepicker').datepicker({
      autoclose: true
    })
  })
</script>

   <script type="text/javascript">
  $(document).ready(function() {
    $('#example12').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
            },
        ]
    } );
} );
  </script>
  
<script>
  $(function () {
    //Date picker
    $('#datepicker1').datepicker({
      autoclose: true
    })
  })
</script>
<script>
  $(function () {
    //Date picker
    $('#datepicker2').datepicker({
      autoclose: true
    })
  })
</script>

<script>
  $(function () {
    $('.textarea').wysihtml5()
  })
</script>

@include('layouts.notification')

accurate/admin/accu/resources/views/layouts/menu.blade.php
<ul class="sidebar-menu" data-widget="tree">

        <li class="header">MAIN NAVIGATION</li>
        <li><a href="{{URL::to('/')}}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
       
        <!-- Category Management -->
         <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-th"></i>
            <span>Category Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a href="{{route('category.index')}}"><i class="fa fa-circle-o"></i>Category</a></li>
              <li><a href="{{route('sub_category.index')}}"><i class="fa fa-circle-o"></i>SubCategory</a></li>
              <li><a href="{{route('sub_sub_category.index')}}"><i class="fa fa-circle-o"></i>SubSubCategory</a></li>
              <li><a href="{{route('sub_sub_sub_category.index')}}"><i class="fa fa-circle-o"></i>SubSubSubCategory</a></li>
          </ul>
        </li>

        <!-- Inventory Management -->
        <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-folder-close"></i>
            <span>Inventory Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{route('product.create')}}"><i class="fa fa-circle-o"></i>Create Product</a></li>
              <li><a href="{{route('product.index')}}"><i class="fa fa-circle-o"></i>View Product</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-percent"></i>
            <span>Voucher</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{route('voucher.index')}}"><i class="fa fa-circle-o"></i>Voucher List</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-th"></i>
            <span>CMS</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{route('banner.index')}}"><i class="fa fa-circle-o"></i>Banner</a></li>
             <li><a href="{{route('pages.index')}}"><i class="fa fa-circle-o"></i>Pages</a></li>
          </ul>
        </li> 

           <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-shopping-cart"></i>
            <span>Order Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu"><!-- 
             <li><a href="{{route('orders.show',0)}}"><i class="fa fa-circle-o"></i>New Orders</a></li> -->
          </ul>
        </li> 

        <!-- user List -->
         <li class="treeview">
          <a href="#">
            <i class="fa fa-user"></i>
            <span>User Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{route('user.index')}}"><i class="fa fa-circle-o"></i>User List</a></li>
          </ul>
        </li>


        <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-cog"></i>
            <span>Settings</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{{route('roles.index')}}"><i class="fa fa-circle-o"></i>Roles</a></li>
             <li><a href="{{route('users.index')}}"><i class="fa fa-circle-o"></i>Users</a></li>
          </ul>
        </li>

          

      </ul>

accurate/admin/accu/resources/views/layouts/notification.blade.php
<script>
    @if(count($errors) > 0)
        @foreach($errors->all() as $error)
            toastr.error("{{ $error }}");
        @endforeach
    @endif
</script>
<script>
  @if(Session::has('success'))
  		toastr.success("{{ Session::get('success') }}");
  @endif
  @if(Session::has('info'))
  		toastr.info("{{ Session::get('info') }}");
  @endif
  @if(Session::has('warning'))
  		toastr.warning("{{ Session::get('warning') }}");
  @endif
  @if(Session::has('error'))
  		toastr.error("{{ Session::get('error') }}");
  @endif
</script>