footwear/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');
/* Admin Category Controller */
Route::resource('category','Admin\CategoryController');
/* Admin Unversity Controller */
Route::resource('university','Admin\UniversityController');
/* Admin Content Controller */
Route::resource('content','Admin\ContentController');

footwear/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
USe App\Model\Admin\Category;
USe Session;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $indexes = Category::all();
        return view('admin.category.index',compact('indexes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return  view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
        'category'    => 'required',
        'subcategory' => 'required'
    ]);

       $category = Category::create([
        'categories'    => $request->category,
        'subcategory' => $request->subcategory
    ]);

       if ($category) {
           Session::flash('success','Category Created Successfully');
       }
       else{
        Session::flash('error','Category not created');
       }

       return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $delete = Category::find($id);

        if ($delete->status == 1 ) {
           $delete->status = '0';
           $delete->save();
        }
        else{
           $delete->status = '1';
           $delete->save();
        }
        return redirect()->route('category.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $update = Category::find($id);
        return  view('admin.category.edit',compact('update'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
        'category'    => 'required',
        'subcategory' => 'required'
    ]);

       $category = Category::where('id',$id)->update([
        'categories'  => $request->category,
        'subcategory' => $request->subcategory
    ]);

       if ($category) {
           Session::flash('success','Category Created Successfully');
       }
       else{
        Session::flash('error','Category not created');
       }
       
       return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

footwear/resources/views/admin/category/create.blade.php
 @extends('admin.layouts.app')

 @section('page-css')
 
 @endsection

 @section('content')
     <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Forms</a></li>
                                            <li class="breadcrumb-item active">Validation</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Create Category</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">Create Category Here</h4>                                        

                                        <form class="needs-validation" novalidate action="{{route('category.store')}}" method="post">
                                        	@csrf
                                           
                                            <div class="form-group mb-3">
                                                <label for="validationCustom03">Category</label>
                                                <input type="text" class="form-control" id="validationCustom03" name="category" placeholder="Category" required>
                                                <div class="invalid-feedback">
                                                    Please provide a valid Category.
                                                </div>
                                            </div>
                                            <div class="form-group mb-3">
                                                <label for="validationCustom04">Subcategory</label>
                                                <input type="text" class="form-control" id="validationCustom04" name="subcategory" placeholder="Subcategory" required>
                                                <div class="invalid-feedback">
                                                    Please provide a valid Subcategory.
                                                </div>
                                            </div>
                                            <button class="btn btn-primary" type="submit">Create</button>
                                        </form>

                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div> <!-- end col-->


                        </div>
                        <!-- end row -->


                    </div> <!-- container -->

                </div> <!-- content -->

            </div>

 @endsection

 @section('footer-js')
<!-- Validation init js-->
        <script src="{{URL::to('admin/js/pages/form-validation.init.js')}}"></script>
 @endsection

footwear/resources/views/admin/category/edit.blade.php
 @extends('admin.layouts.app')

 @section('page-css')
 
 @endsection

 @section('content')
     <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Forms</a></li>
                                            <li class="breadcrumb-item active">Validation</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Update Category</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">Edit Category Here</h4>                                        

                                        <form class="needs-validation" novalidate action="{{route('category.update',$update->id)}}" method="post">
                                        	@csrf
                                            @method('put')
                                           
                                            <div class="form-group mb-3">
                                                <label for="validationCustom03">Category</label>
                                                <input type="text" class="form-control" id="validationCustom03" name="category" value="{{$update->categories}}" required>
                                                <div class="invalid-feedback">
                                                    Please provide a valid Category.
                                                </div>
                                            </div>
                                            <div class="form-group mb-3">
                                                <label for="validationCustom04">Subcategory</label>
                                                <input type="text" class="form-control" id="validationCustom04" name="subcategory" value="{{$update->subcategory}}" required>
                                                <div class="invalid-feedback">
                                                    Please provide a valid Subcategory.
                                                </div>
                                            </div>
                                            <button class="btn btn-primary" type="submit">Update</button>
                                        </form>

                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div> <!-- end col-->


                        </div>
                        <!-- end row -->


                    </div> <!-- container -->

                </div> <!-- content -->

            </div>

 @endsection

 @section('footer-js')
<!-- Validation init js-->
        <script src="{{URL::to('admin/js/pages/form-validation.init.js')}}"></script>
 @endsection

footwear/resources/views/admin/category/index.blade.php
@extends('admin.layouts.app')

@section('page-css')
 <!-- third party css -->
        <link href="admin/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="admin/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="admin/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="admin/libs/datatables.net-select-bs4/css//select.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <!-- third party css end -->
@endsection

@section('content')
 <div class="content-page">
 	 <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <a href="{{route('category.create')}}" class="btn btn-info">Create category</a>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Category List</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        

                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">

                                        <!-- <h4 class="header-title">Category LIst</h4> -->

                                        <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Categories</th>
                                                    <th>Subcategories</th>
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                        
                                        
                                            <tbody>
                                                @php $i = 1; @endphp
                                              @foreach( $indexes as $index )
                                                <tr>
                                                    <td>{{$i++}}</td>
                                                    <td>{{$index->categories}}</td>
                                                    <td>{{$index->subcategory}}</td>
                                                    <td>
                                                        @if($index->status == 1)
                                                        <span class="text-success"><strong>Active</strong></span>
                                                        @else
                                                        <span class="text-danger"><strong>Inactive</strong></span>
                                                        @endif
                                                    </td>
                                                    <td>
                                                        <a href="{{route('category.edit',$index->id)}}" class="btn btn-warning btn-xs">Edit</a>

                                                        @if($index->status == 1 )
                                                        <a href="{{route('category.show',$index->id)}}" class="btn btn-danger btn-xs">Inactive</a>
                                                        @else
                                                        <a href="{{route('category.show',$index->id)}}" class="btn btn-success btn-xs">Active</a>
                                                        @endif
                                                    </td>
                                                </tr>                       
                                              @endforeach                        
                                            </tbody>
                                        </table>
                                        
                                    </div> <!-- end card body-->
                                </div> <!-- end card -->
                            </div><!-- end col-->
                        </div>
                        <!-- end row-->



                        
                    </div> <!-- container -->

                </div> <!-- content -->
 </div>
@endsection

@section('footer-js')
 <!-- third party js -->
        <script src="admin/libs/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="admin/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
        <script src="admin/libs/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
        <script src="admin/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
        <script src="admin/libs/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
        <script src="admin/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
        <script src="admin/libs/datatables.net-buttons/js/buttons.html5.min.js"></script>
        <script src="admin/libs/datatables.net-buttons/js/buttons.flash.min.js"></script>
        <script src="admin/libs/datatables.net-buttons/js/buttons.print.min.js"></script>
        <script src="admin/libs/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
        <script src="admin/libs/datatables.net-select/js/dataTables.select.min.js"></script>
        <script src="admin/libs/pdfmake/build/pdfmake.min.js"></script>
        <script src="admin/libs/pdfmake/build/vfs_fonts.js"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="admin/js/pages/datatables.init.js"></script>
         @endsection