accurate/admin/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function(){
 
 		/*user*/
 		Route::resource('user', 'User\UserController');

		Route::resource('roles','Roles\RoleController');
		Route::resource('users','Roles\UserController');
		Route::resource('banner','CMS\BannerController');
        Route::resource('pages','CMS\PagesController');
		/*Category*/
		Route::resource('category','Category\CategoryController');
		Route::resource('sub_category','Category\SubCategoryController');
		Route::resource('sub_sub_category','Category\SubSubCategoryController');
		Route::resource('sub_sub_sub_category','Category\SubSubSubContoller');

		/*Voucher*/
		Route::resource('voucher','Voucher\VoucherController');

		/*Inventory*/
		Route::resource('product','Inventory\ProductController');
		Route::resource('product_size','Inventory\ProductsizeController');
		Route::resource('stock','Inventory\StockController');

		/*query Section*/
		Route::get('support/query','Query\QueryController@view_support');
		Route::get('training/query','Query\QueryController@view_training');
		Route::get('contact/query','Query\QueryController@view_contact');

		/*Pincode Section*/
		Route::resource('pincode','Pincode\PincodeController');
		Route::get('pincode/delete/{id}','Pincode\PincodeController@delete')->name('pincode.delete');

		/*Orders*/
		Route::resource('orders','Order\OrderController');
		/* Category */
		Route::resource('quiz','Quiz\QuizController');
		 /* Question */
		Route::resource('question','Quiz\QuestionsController');

});

Route::get('file_download/{id}','Website\WebsiteController@index');

accurate/admin/app/Http/Controllers/Inventory/ProductController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Http\Controllers\Controller; 
use App\Model\Inventory\Product;
use Illuminate\Http\Request;
use DB;
use Session;
use Yajra\DataTables\DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
      
      public function index()
    {   

        $query =Product::query();
         
         /*Run ALL The Query*/
        $data = $query->join('categories','categories.id','products.category_id')
                      ->join('sub__categories','sub__categories.id','products.sub_category_id')
                      ->leftjoin('sub__sub__categories','sub__sub__categories.id','products.sub_sub_category_id')
                      ->select('products.*','categories.category','sub__categories.sub_category','sub__sub__categories.sub_sub_category')
                      ->orderby('id','DESC')
                      ->paginate(16);

        $category = DB::table('categories')->get();
        return view('Admin.Inventory.Product.view_product',compact('data','category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = DB::table('categories')->get();
        return view('Admin.Inventory.Product.create_product',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         request()->validate([
            'category_id'              => 'required|Integer',
            'subcategory_id'           => 'required|Integer',
            'subsubcategory_id'        => 'nullable|Integer',
            'sub_sub_sub_category_id'  => 'nullable|Integer',
            'meta_title'               => 'nullable',
            'meta_keywords'            => 'nullable',
            'title'                    => 'required|string|unique:products',
            'image'                    => 'required',
            'description'              => 'required|string',
            'amount'                   => 'required|Integer'
        ]);

         //dd($request->all());

        $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$request->image->getClientOriginalName();
        $request->image->move('img/product', $image_name);

        $insert = new Product;
        $insert->category_id             = $request->category_id;
        $insert->sub_category_id         = $request->subcategory_id;
        $insert->sub_sub_category_id     = $request->subsubcategory_id;
        $insert->sub_sub_sub_category_id = $request->sub_sub_sub_category_id;
        $insert->meta_title              = $request->meta_title;
        $insert->meta_keyword            = $request->meta_keywords;
        $insert->title                   = $request->title;
        $insert->main_image              = $image_name;
        $insert->description             = $request->description;
        $insert->amount                  = $request->amount;
        $insert->status                  = 1;
        $insert->save();

        Session::flash('success','Product Enlist Successfully');
        return redirect()->route('product.edit',$insert->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $data = DB::table('product_file')->where('product_id',$id)->get();
        return view('Admin.Inventory.Product.file',compact('id','data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {   
        $category = DB::table('categories')->get();
        $sub_category = DB::table('sub__categories')->where('id',$product->sub_category_id)->get();
        $sub_sub_category = DB::table('sub__sub__categories')->where('id',$product->sub_sub_category_id)->get();
        $sub_sub_sub_category = DB::table('sub_sub_sub_category')->get();
        return view('Admin.Inventory.Product.edit_product',compact('category','product','sub_category','sub_sub_category','sub_sub_sub_category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        request()->validate([
            'category_id'       => 'required|Integer',
            'subcategory_id'    => 'required|Integer',
            'subsubcategory_id' => 'nullable|Integer',
            'title'             => 'required|string',
            'meta_title'        => 'nullable',
            'meta_keywords'     => 'nullable',
            'image'             => 'nullable',
            'description'       => 'required|string',
            'amount'            => 'required',
            'status'            => 'required',
        ]);

        if (isset($request->image)) {

            $file_check = file_exists('img/product/'.$product->main_image);
            if ($file_check == true) {            
                unlink('img/product/'.$product->main_image);
            }

            $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$request->image->getClientOriginalName();
            $request->image->move('img/product', $image_name);
        }
        else
        {
            $image_name = $product->main_image;
        }
    

        $insert = Product::find($product->id);
        $insert->category_id         = $request->category_id;
        $insert->sub_category_id     = $request->subcategory_id;
        $insert->sub_sub_category_id = $request->subsubcategory_id;
        $insert->meta_title          = $request->meta_title;
        $insert->meta_keyword        = $request->meta_keywords;
        $insert->title               = $request->title;
        $insert->main_image          = $image_name;
        $insert->description         = $request->description;
        $insert->amount              = $request->amount;
        $insert->status              = $request->status;
        $insert->save();

        Session::flash('success','Product Update Successfully');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $data =  DB::table('product_file')->where('id',$id)->first();

       $file_check = file_exists('img/product/'.$data->files);
        if ($file_check == true) {            
            unlink('img/product/'.$data->files);
        }

        DB::table('product_file')->where('id',$id)->delete();

        Session::flash('success','Files Successfully Delete');
        return back();
    }
}

accurate/admin/app/Http/Controllers/Inventory/ProductsizeController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Http\Controllers\Controller;
use App\Model\Inventory\Productsize;
use Illuminate\Http\Request;
use Session;
use Carbon\Carbon;
use DB;

class ProductsizeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(request $request)
    {
       request()->validate([
            'id'        => 'required',
            'file_type' => 'required',
            'file'      => 'required'
       ]);

       if ($request->file_type == 2) {
           $image_name = $request->file;
       }
       else{
            $image_name  =strtotime(date('Y-m-d H:i:s')).'_'.$request->file->getClientOriginalName();
            $request->file->move('img/product', $image_name);
       }

       DB::table('product_file')->insert([
            'product_id'  => $request->id,
            'file_type'   => $request->file_type,
            'files'       => $image_name,
            'created_at'  => Carbon::now(),
       ]);

       Session::flash('success','Data Successfully Insert');
       return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(request $request)
    {
        request()->validate([
            'id'         => 'required',
            'attribute'  => 'required',
            'type'       => 'required',
        ]);

        $check = DB::table('product_attribute')->where('product_id',$request->id)
                                               ->where('atribute',$request->attribute)
                                               ->where('type',$request->type)
                                               ->first();

        if ($check) {
            Session::flash('error','Data Already exist');
        }
        else
        {
            DB::table('product_attribute')->insert([
            'product_id'  => $request->id,
            'atribute'    => $request->attribute,
            'type'        => $request->type,
            'created_at'  => Carbon::now(),
           ]);

           Session::flash('success','Data Successfully Insert');
        }
         
       return back();

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'id'     => 'required',
           // 'size'   => 'required',
            'weight' => 'required',
            'amount' => 'required|integer',
        ]);

        //$check = Productsize::where('product_id',$request->id)->where('size',$request->size)->first();
        $check = Productsize::where('product_id',$request->id)->where('weight',$request->weight)->first();
        if (!$check) {
            $insert = new Productsize;
            $insert->product_id  = $request->id;
            //$insert->size        = $request->size;
            $insert->weight      = $request->weight;
            $insert->amount      = $request->amount;
            $insert->save();

            Session::flash('success','Insert Successfully');
        }
        else{
            Session::flash('error','Already Exist');
        }

        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Productsize  $productsize
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = DB::table('product_attribute')->where('product_id',$id)->get();
        return view('Admin.Inventory.Product.attribute',compact('id','data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Productsize  $productsize
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $data = Productsize::where('product_id',$id)->get();
        return view('Admin.Inventory.Product.product_size',compact('id','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Productsize  $productsize
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'status' => 'required',
            'weight' => 'required',
            'amount' => 'required|integer',
        ]);

            $insert = Productsize::find($id);
            $insert->weight      = $request->weight;
            $insert->amount      = $request->amount;
            $insert->status      = $request->status;
            $insert->save();

         Session::flash('success','Update Successfully');

         return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Productsize  $productsize
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('product_attribute')->where('id',$id)->delete();

         Session::flash('success','Delete Successfully');

         return back();

    }
}

accurate/admin/app/Http/Controllers/Inventory/StockController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Http\Controllers\Controller;
use App\Model\Inventory\Product;
use App\Model\Inventory\Stock;
use Illuminate\Http\Request;
use DB;
use Session;


class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('products')->join('stocks','stocks.product_id','products.id')
                                     ->groupBy('stocks.size')
                                     ->groupBy('products.title')
                                     ->groupBy('stocks.product_id')
                                     ->select('products.title','stocks.product_id','stocks.size',DB::raw('sum(stocks.credit) as credit'),DB::raw('sum(stocks.debit) as debit'))
                                     ->get();

        return view('Admin.Inventory.stocks',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'size'    => 'required',
            'credit'  => 'required',
            'id'      => 'required',
        ]);

        $insert = new Stock;
        $insert->product_id = $request->id;
        $insert->size       = $request->size;
        $insert->credit     = $request->credit;

        $insert->save();

         Session::flash('success','Insert Successfully');
         return back();
    }   

    /**
     * Display the specified resource.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function show(Stock $stock)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $size = DB::table('productsizes')->where('product_id',$id)->get();
        $data = Stock::where('stocks.product_id',$id)->join('productsizes','productsizes.id','=','stocks.size')
                                         ->select('productsizes.id','productsizes.weight as size','stocks.credit','stocks.debit','stocks.created_at')
                                         ->orderby('id','DESC')
                                         ->get();

        return view('Admin.Inventory.Product.stock',compact('id','size','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stock $stock)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stock $stock)
    {
        //
    }
}

accurate/admin/resources/views/Admin/Inventory/Product/attribute.blade.php
<title>Product List</title>
@extends('layouts.admin')
@section('content')
<section class="content-header">
   <h1>
      Product List
   </h1>
   <ol class="breadcrumb">
      <!-- <a href="#" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> </a> -->
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">
   <div class="col-xs-12">
      <div class="box box-primary">
         <ul class="nav nav-tabs">
            <li><a href="{{route('product.edit',$id)}}">Edit Product</a></li>
            <li><a href="{{route('product_size.edit',$id)}}">Product Size</a></li>
            <!-- <li class="active"><a href="{{route('product_size.show',$id)}}">Product Atribute</a></li> -->
            <li><a href="{{route('stock.edit',$id)}}">Stock</a></li>
            <li><a href="{{route('product.show',$id)}}">File</a></li>
         </ul>
         <!-- /.box-header -->
         <!-- form start -->
         <form role="form" action="{{route('product_size.create')}}" method="post" enctype="multipart/form-data">
          @csrf
          @method('GET')
          <input type="hidden" name="id" value="{{$id}}">
            <div class="box-body">
               <div class="col-md-6">
                  <div class="form-group">
                     <label>Attribute</label>
                      <select class="form-control" name="attribute">
                          <option>Color</option>
                      </select>
                  </div>
               </div>

               <div class="col-md-6">
                  <div class="form-group">
                     <label>Type</label>
                     <select class="form-control" name="type">
                          <option>Yellow</option>
                          <option>White</option>
                          <option>Black</option>
                      </select>
                  </div> 
               </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
               <button type="submit" class="btn btn-primary">Submit</button>
            </div>
         </form>
      </div>
   </div>

   <div class="col-xs-12">
      <div class="box box-primary">
         <div class="box-body" style="overflow-y: auto;">
            <table class="table table-bordered table-striped">
               <thead>
                  <tr>
                      <th>Attribute</th>
                      <th>Type</th>
                      <th>Action</th>
                  </tr>
               </thead>
               <tbody>
                    
                    @foreach($data as $datas)

                      <tr>
                        <td>{{$datas->atribute}}</td>
                        <td>{{$datas->type}}</td>
                        <td>
                          <a href="">
                            <form action="{{route('product_size.destroy',$datas->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                              <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i></button>
                            </form>
                          </a>
                        </td>
                      </tr>

                    @endforeach
                   
                 
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <!-- /.row -->
</section>
@endsection


<script type="text/javascript">
   function sizes(element){
    var sizes = $(element).val();    
    if(sizes){
        $.ajax({
           type:"GET",
           url:"{{URL::to('price')}}/"+sizes+'/',
           success:function(res){               
            if(res){
                if (res.length == 0) {
                   $("#default_size").empty();
                   $("#size_type").empty();
                   $("#size_type").append('<option>None</option>');
                   $("#default_size").append('<option>None</option>');
                }
                else
                {
                    $("#default_size").empty();
                    $("#default_size").append('<option>Select Default Size</option>');
                    $("#size_type").empty();
                    $.each(res,function(key,value){
                        $("#size_type").append('<option value="'+key+'">'+key+''+value+'</option>');
                    });
                    $.each(res,function(key,value){
                        $("#default_size").append('<option value="'+key+'">'+key+''+value+'</option>');
                    });
                }   
            }
           }
        });
    }     
    };
</script>

accurate/admin/resources/views/Admin/Inventory/Product/product_size.blade.php
<title>Product List</title>
@extends('layouts.admin')
@section('content')
<section class="content-header">
   <h1>
      Product List
   </h1>
   <ol class="breadcrumb">
      <!-- <a href="#" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> </a> -->
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">
   <div class="col-xs-12">
      <div class="box box-primary">
         <ul class="nav nav-tabs">
            <li><a href="{{route('product.edit',$id)}}">Edit Product</a></li>
            <li class="active"><a href="{{route('product_size.edit',$id)}}">Product Size</a></li>
            <!-- <li><a href="{{route('product_size.show',$id)}}">Product Atribute</a></li> -->
            <li><a href="{{route('stock.edit',$id)}}">Stock</a></li>
            <li><a href="{{route('product.show',$id)}}">File</a></li>
         </ul>
         <!-- /.box-header -->
         <!-- form start -->
         <form role="form" action="{{route('product_size.store')}}" method="post" enctype="multipart/form-data">
          @csrf
          <input type="hidden" name="id" value="{{$id}}">
            <div class="box-body">
               <!-- <div class="col-md-4">
                  <div class="form-group">
                     <label>Size</label>
                     <input type="text" name="size" class="form-control" required placeholder="Enter Product Size">
                  </div>
               </div> -->
               <div class="col-md-4">
                  <div class="form-group">
                     <label>Weight</label>
                     <input type="text" name="weight" class="form-control" required placeholder="Enter Product Weight">
                  </div> 
               </div>
               <div class="col-md-4">
                  <div class="form-group">
                     <label>Amount</label>
                     <input type="number" name="amount" class="form-control" required placeholder="Enter Product Amount">
                  </div>
               </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
               <button type="submit" class="btn btn-primary">Submit</button>
            </div>
         </form>
      </div>
   </div>

   <div class="col-xs-12">
      <div class="box box-primary">
         <div class="box-body" style="overflow-y: auto;">
            <table class="table table-bordered table-striped">
               <thead>
                  <tr>
                      <!-- <th>Size</th> -->
                      <th>Weight</th>
                      <th>Amount</th>
                      <th>Status</th>
                      <th>Action</th>
                  </tr>
               </thead>
               <tbody>
                    
                    @foreach($data as $datas)

                      <tr>
                        <!-- <td>{{$datas->size}}</td> -->
                        <td>{{$datas->weight}}</td>
                        <td>{{$datas->amount}}</td>
                        <td>
                          @if($datas->status == 1)
                               Active
                          @else
                                DeActive
                          @endif
                        </td>
                        <td>
                          <button class="btn btn-primary" data-toggle="modal" data-target="#text{{$datas->id}}"><i class="glyphicon glyphicon-edit"></i> </button>
                                    <div class="modal fade" id="text{{$datas->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                       <div class="modal-content">
                                          <div class="modal-header">
                                            <h4 class="modal-title" id="myModalLabel">Edit Price</h4>
                                          </div>
                                             <div class="modal-body">
                                                <form role="form" action="{{route('product_size.update',$datas->id)}}" method="Post" >
                                                    @csrf
                                                    @method('PUT')
                                                       
                                                   <label>Weight</label>
                                                    <input type="" class="form-control" name="weight" value="{{$datas->weight}}">

                                                  <label>Price</label>
                                                    <input type="number" class="form-control" name="amount" value="{{$datas->amount}}" step="0.01">

                                                   <label>Status</label>
                                                    <select class="form-control" name="status">
                                                        <option value="1">Active</option>
                                                        <option value="0">DeActive</option>
                                                    </select>
                                                 
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-primary" value="submit">Submit</button>
                                                  </div>
                                                  </form>
                                              </div>
                                          </div>
                                     </div>
                        </td>

                      </tr>

                    @endforeach
                   
                 
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <!-- /.row -->
</section>
@endsection


<script type="text/javascript">
   function sizes(element){
    var sizes = $(element).val();    
    if(sizes){
        $.ajax({
           type:"GET",
           url:"{{URL::to('price')}}/"+sizes+'/',
           success:function(res){               
            if(res){
                if (res.length == 0) {
                   $("#default_size").empty();
                   $("#size_type").empty();
                   $("#size_type").append('<option>None</option>');
                   $("#default_size").append('<option>None</option>');
                }
                else
                {
                    $("#default_size").empty();
                    $("#default_size").append('<option>Select Default Size</option>');
                    $("#size_type").empty();
                    $.each(res,function(key,value){
                        $("#size_type").append('<option value="'+key+'">'+key+''+value+'</option>');
                    });
                    $.each(res,function(key,value){
                        $("#default_size").append('<option value="'+key+'">'+key+''+value+'</option>');
                    });
                }   
            }
           }
        });
    }     
    };
</script>